GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes/
content-type: application/json

{
	"content": "Some content"
}

###

POST http://localhost:3001/api/notes/
content-type: application/json

{
	"content": "Some important content",
	"important": true
}

### Malformed request (too short content)
POST http://localhost:3001/api/notes/
content-type: application/json

{
	"content": "lol",
	"important": true
}


